/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as BrokerRouteImport } from './routes/broker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardClientIdRouteImport } from './routes/dashboard.$clientId'
import { Route as BrokerClientIdRouteImport } from './routes/broker.$clientId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRoute = BrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientIdRoute = DashboardClientIdRouteImport.update({
  id: '/dashboard/$clientId',
  path: '/dashboard/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerClientIdRoute = BrokerClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => BrokerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broker': typeof BrokerRouteWithChildren
  '/upload': typeof UploadRoute
  '/broker/$clientId': typeof BrokerClientIdRoute
  '/dashboard/$clientId': typeof DashboardClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/broker': typeof BrokerRouteWithChildren
  '/upload': typeof UploadRoute
  '/broker/$clientId': typeof BrokerClientIdRoute
  '/dashboard/$clientId': typeof DashboardClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/broker': typeof BrokerRouteWithChildren
  '/upload': typeof UploadRoute
  '/broker/$clientId': typeof BrokerClientIdRoute
  '/dashboard/$clientId': typeof DashboardClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/broker'
    | '/upload'
    | '/broker/$clientId'
    | '/dashboard/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/broker' | '/upload' | '/broker/$clientId' | '/dashboard/$clientId'
  id:
    | '__root__'
    | '/'
    | '/broker'
    | '/upload'
    | '/broker/$clientId'
    | '/dashboard/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrokerRoute: typeof BrokerRouteWithChildren
  UploadRoute: typeof UploadRoute
  DashboardClientIdRoute: typeof DashboardClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$clientId': {
      id: '/dashboard/$clientId'
      path: '/dashboard/$clientId'
      fullPath: '/dashboard/$clientId'
      preLoaderRoute: typeof DashboardClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker/$clientId': {
      id: '/broker/$clientId'
      path: '/$clientId'
      fullPath: '/broker/$clientId'
      preLoaderRoute: typeof BrokerClientIdRouteImport
      parentRoute: typeof BrokerRoute
    }
  }
}

interface BrokerRouteChildren {
  BrokerClientIdRoute: typeof BrokerClientIdRoute
}

const BrokerRouteChildren: BrokerRouteChildren = {
  BrokerClientIdRoute: BrokerClientIdRoute,
}

const BrokerRouteWithChildren =
  BrokerRoute._addFileChildren(BrokerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrokerRoute: BrokerRouteWithChildren,
  UploadRoute: UploadRoute,
  DashboardClientIdRoute: DashboardClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
